### ISSUE TITLE
Error when trying to use softchat with Twitch live chat recordings

### ISSUE THREAD

**Issue by KaMyKaSii** [9001/softchat#11]
I just discovered your program and it worked well to create subtitles using a Twitch VOD and the full VOD chat. Now I'm trying to do the same for Twitch broadcasts that don't have VOD available, recording live through streamlink and with chat_downloader saving the chat simultaneously, but unfortunately I always get the following error:

```
Traceback (most recent call last):
  File "/home/matheus/.venv/bin/softchat", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/matheus/.venv/lib/python3.12/site-packages/softchat/__main__.py", line 578, in main
    raise Exception("no messages were loaded" + use_018)
Exception: no messages were loaded; please use softchat v0.18 or older if your chat json was created with a chat_replay_downloader from before 2021-01-29-something
```

Commands used:
`streamlink --output "/media/matheus/Ventoy/vods/yayahuz/{time}_{author}_{id}.mkv" "https://twitch.tv/yayahuz" best`
`chat_downloader "https://twitch.tv/yayahuz" -o "/home/matheus/Downloads/chat_downloader/$(date "+%F_%H-%M-%S")-yayahuz.json" -q`
`softchat -m1 --fontdir "/home/matheus/Downloads/noto-hinted" --media "/media/matheus/Ventoy/vods/yayahuz/2024-11-11_23-45-20_yayahuz_52403683245.mkv" "/home/matheus/Downloads/chat_downloader/2024-11-11_23-45-18-yayahuz.json" -r 1920x1080 -b 600x500+20+50 --sz 24 --badge_sz 1`

I also tried providing the start_time (converting the date in the media file name to UTC with "date -d "${date} -3" -u +%s") but got the same error

KDE Neon 24.04
Python 3.12.3
chat-downloader 0.2.8
softchat 1.7

**Comment by 9001** [comment]
thanks, you're probably the first person to try this on a twitch live. Should be fixed in the latest ver :+1: 

though I noticed that both mpv and vlc struggled with showing the subtitles after embedding them into the mkv... fortunately it plays correctly if you load the .ass into the player separately, so I think that'll be a challenge for another day.

**Comment by KaMyKaSii** [comment]
> thanks, you're probably the first person to try this on a twitch live. Should be fixed in the latest ver 👍
> 
> though I noticed that both mpv and vlc struggled with showing the subtitles after embedding them into the mkv... fortunately it plays correctly if you load the .ass into the player separately, so I think that'll be a challenge for another day.

Dude, I'm in love with you. For many years I've wanted a way to save the chat from a Twitch stream into a subtitle file, but the closest thing I've come to that after a lot of research is using TwitchDownloader, but it's only possible to download the chat from public VODs and the program renders the chat into a separate video file to be burned into the VOD using some video editing software. Your program, together with the chat-downloader, allows you to quickly create a subtitle file that can be viewed in a regular video player without having to spend processing and time burning the chat into the video stream, which is all I wanted. Thank you very much!

I tested it twice, once using the media from the live recording via streamlink and another with the media from the VOD downloading (which is divided into 3 parts so that it can be uploaded to Telegram respecting the 2000MiB file size limit) and both tests generated functional subtitle files with the expected synchronization. But in the second case, the program returned an error in the terminal. Maybe it's because the file duration (the first part) is less than the total chat duration?
![Screenshot_20241116_220140](https://github.com/user-attachments/assets/ee56b142-a1b8-4045-a9e0-d44fd61e4470)

About embedding the subtitle file in the mkv file, I tested it and had no problems. The subtitles appear exactly the same way as when loaded externally and when seeking the synchronization continues as expected, the only thing I could notice is that when seeking in VLC the subtitle disappears for a second until VLC shows it again. How did you embed the subtitles in the file? I did it with the following command in ffmpeg (I used concat to merge the three parts back into a single video file again, in your case it is not necessary): `ffmpeg -stats -f concat -i "concat.txt" -i 2024-11-11_23-32-22_yayahuz_52403683245_video-part1.mkv.ass -map 0 -map 1 -c copy "vod-with-softsub.mkv"`

I decided to test enabling emotes but the program returns "you requested --emote_font but fontforge is not installed" even after following the steps to install the dependencies for Debian (I have KDE Neon, based on Ubuntu 24.04), do you have any idea why?
![image](https://github.com/user-attachments/assets/184f8705-8c11-4e90-95d2-69dd3e46ab11)
