### ISSUE TITLE
Unable to see graphical emotes

### ISSUE THREAD

**Issue by suwagawaki** [9001/softchat#8]
Hello! I'm having issues having graphical emotes display. I used --emote_font with --emote_install and only see empty boxes for what I assume are supposed to be emotes. The /emotes directory is populated with the emote data, as well. 

Update: Installed the font .ttf produced by softchat directly to my system fonts directory instead of the directory used by --emote_install, the empty boxes have disappeared but no graphical emotes are displayed.

**Comment by 9001** [comment]
Hey o/
Could you try `--embed_files` and see if that works? Also, especially regarding the edit, what media player / OS / os-language are you on? I'm on the move rn so sorry for the short replies 👍

Edit: oh and how big is the emotes ttf?

**Comment by suwagawaki** [comment]
No worries about the short replies :v: I'm on Win 10 English, using mpv. 

I'm attempting `--embed_files` at the moment, I think the files may just be too large in general? The chat downloader .json is ~183mb and the VOD itself (~4hrs41m) is almost 13gb. The .ttf is 25kb. The /emotes directory has 2672 files.

```
python -m softchat -m2 --embed_files same.json same.mp4
04:44:42.511 found fugashi
04:44:42.512 fontsize 24 pt
04:44:42.515 found font: D:\softchat\noto-hinted\SquishedNotoSansCJKjp-Regular.otf
04:44:42.529 loading same.json
04:44:44.528 loading same.mp4
Traceback (most recent call last):
  File "C:\Users\mini\AppData\Roaming\Python\Python311\site-packages\softchat\__main__.py", line 381, in main
    jd2 = json.load(f)
          ^^^^^^^^^^^^
  File "C:\Users\mini\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
  File "<frozen codecs>", line 504, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 35: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mini\AppData\Roaming\Python\Python311\site-packages\softchat\__main__.py", line 1265, in <module>
    main()
  File "C:\Users\mini\AppData\Roaming\Python\Python311\site-packages\softchat\__main__.py", line 383, in main
    err = repr(ex)
          ^^^^^^^^
MemoryError

```

**Comment by awused** [comment]
Those files aren't particularly large, in fact that's a really small ttf. Sounds like your media player isn't loading the font or otherwise needs to be configured properly.

**Comment by 9001** [comment]
Yeah that should work for sure -- and the reason it crashed just now was cause it tried to load the video file as json :p should add a better error message for that!

how's this?

```
python -m softchat -m2 --emote_font --emote_cache emotes --embed_files same.json
```

**Comment by suwagawaki** [comment]
Ahhh, that was my assumption as well watching the memory fill up during the process 😂 

```
05:19:29.281 writing 4:39:38.00, #107001 / 108469
05:19:29.331 writing 4:43:42.00, #108001 / 108469
05:19:29.360 could not verify chat duration: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
05:19:29.360 you requested --embed_files but the media file could not be located
05:19:29.361 finished in 36.94 sec
```

**Comment by 9001** [comment]
Aw, alright let's help it a bit by adding `--media same.mp4`

**Comment by suwagawaki** [comment]
`python -m softchat -m2 --emote_font --emote_cache emotes --embed_files same.json --media same.mp4`

Tried `--media D:\same\same.mp4` as well, same result:

```
05:38:54.217 writing 4:43:42.00, #108001 / 108469
05:38:54.243 could not verify chat duration: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
05:38:54.243 you requested --embed_files but the media file could not be located
05:38:54.243 finished in 35.37 sec
```
Ran `u` and `uu` for `ytdl-tui` and found updates, will redownload the VOD and see if that helps.

**Comment by suwagawaki** [comment]
Solved it! Just needed to add the ffmpeg path to Windows. 😂

**Comment by suwagawaki** [comment]
Well I was able to get `--embed_files` to work but the output ends up a bit smaller than the original VOD file and the subtitles are not visible at all. 

Just so I'm not misunderstanding how the graphical emotes option works, is it supposed to display the Twitch emotes instead of the emote name? If that's the case, I'm only seeing the text version. (Pog, PogU, PogO, etc.) I also tried attaching the custom font to the .ass, which seems to be a workaround to installing the custom font to the system/mpv font directory. I'm assuming this might be an issue with the fontforge conversion?

To clarify: I'm able to see the danmaku subs when the .ass is external. The softchat-merged output file does not have any subs visible despite having a subtitle track enabled. 


Update:
Opened up the .ttf in fontforge. The `Fontname` is `Untitled1` and the `Family Name` is `SoftChat Custom Emotes b'\x0c-\x90\xa3\xdc\xe7\x0e\xfay\xca5\x88\xee\xe2\xc4\xc1\xa4\xe7E\x9a\xe7\x1a\xdd7\xd0\xdbl\xf8G\x12\xda\xee\xcf\x8f\xa1\x90\xa0\x8c\xad70b\xb9\xfd\xd8?\x88\x95\xad&\xff\x9fQ%\xb5\xb7\xb2K\xd7\x9e\xf5Pb\x8f'`. Is this intended?

**Comment by awused** [comment]
Maybe try a youtube stream since those definitely work. I've personally never tested it with a twitch stream so that'll at least tell us if it's a problem with softchat's twitch support or your setup.

**Comment by suwagawaki** [comment]
Tried a youtube stream, stopped at this step: 

```
00:10:21.193 found fugashi
00:10:21.193 fontsize 24 pt
00:10:21.195 found font: D:\vods\noto-hinted\SquishedNotoSansCJKjp-Regular.otf
00:10:21.208 loading same-filename.json
Traceback (most recent call last):
  File "C:\Users\mini\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mini\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\mini\AppData\Roaming\Python\Python39\site-packages\softchat\__main__.py", line 1265, in <module>
    main()
  File "C:\Users\mini\AppData\Roaming\Python\Python39\site-packages\softchat\__main__.py", line 436, in main
    for sc in emote["shortcuts"]:
TypeError: 'NoneType' object is not iterable
```

**Comment by awused** [comment]
That was fixed in https://github.com/9001/softchat/commit/1d1d9c2abc9cd01f26dbb2e82c1f11b720591379, try git head.

**Comment by suwagawaki** [comment]
I tried the example youtube video referenced in the manual steps, I believe it worked properly but the chat doesn't spam emotes like twitch chatters usually do:
https://cdn.discordapp.com/attachments/1011896540673085520/1063737346635337778/image.png

I also tried this video from Ludwig on youtube: https://www.youtube.com/watch?v=eLGMkW16x00

The emote for https://cdn.discordapp.com/emojis/454412542337482775.webp?size=96&quality=lossless is displayed as D: in the danmaku. Is this the intended output? Just want to clarify the extent of "graphical emotes" being limited to the standard emojis used across multiple platforms vs. custom emotes specific to channels. 

Thanks for your assistance so far, appreciate it!

**Comment by suwagawaki** [comment]
Disregard this post, process worked fine on my server PC. Gonna close this issue finally!

note: Woops, forgot to mention I decided to try installing an older version of FontForge, dated November 2020, instead of the 2023 build I installed initially. Works as expected now!
