### ISSUE TITLE
Error: "failed: does not look like a chatlog"

### ISSUE THREAD

**Issue by Razzorxi** [9001/softchat#9]
Hi, I tried to convert a twitch chatlog, but it's throwing me the following error.

> E:\>python -m softchat -m2 chat.json
> 17:03:57.096 found fugashi
> 17:03:57.096 fontsize 24 pt
> 17:03:57.098 found font: E:\noto-hinted\SquishedNotoSansCJKjp-Regular.otf
> 17:03:57.114 loading chat.json
> 17:03:57.128 failed: does not look like a chatlog

Softchat, chat-downloader and fugashi are all 3 on the latest version available on pip.

Here's the .json file I'm trying to convert.
[chat.json](https://github.com/9001/softchat/files/13812263/chat.json)

Source VOD is https://www.twitch.tv/videos/2018821061 (subscriber only), downloaded via
> python -m chat_downloader --end_time 01:00:00 --message_groups all --cookies E:\cookies.txt --output chat.json https://www.twitch.tv/videos/2018821061

**Comment by 9001** [comment]
Neat, looks like twitch support broke at some point -- please let me know if you run into any additional twitch issues btw, we've mostly been testing this thing on youtube so far :>

Tried it with `--emote_font --emote_cache emotes --embed_files` to get the emotes into the subs too, and seemed to work alright.

Also big thx for helping archive mogra 👍 👍
